apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - hpa-backend.yaml
  - hpa-frontend.yaml
  - pdb-backend.yaml
  - pdb-frontend.yaml

patches:
  - path: patches/backend-ha.yaml
  - path: patches/frontend-ha.yaml
  - path: patches/ingress-tls.yaml
