apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: url-shortener-local
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hrimov/url-shortener-internal.git
    targetRevision: main
    path: k8s/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: url-shortener
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
